config/routes.rb
Butterflyicing::Application.routes.draw do

  resources :gallery_images
  resources :tags
  resources :tag_groups
  resources :users

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'image_manager' => 'image_manager#index'
  post 'image_manager' => 'image_manager#upload'
  delete 'image_manager' => 'image_manager#delete'
  get 'contactus' => 'contactus#index'
  post 'contactus' => 'contactus#send_message'
  get 'home' => 'home'
  get 'gallery/(:id)' => 'gallery#index' , as: :gallery
  get 'thumbnails/(:image_name)' => 'gallery#thumbnails'
  get 'ourcakes' => 'ourcakes#index'
  get 'weddings' => 'weddings#index'
  get 'cookies' => 'cookies#index'
  get 'parties' => 'parties#index'
  get 'contactus' => 'contactus#index'

  root :to => 'home#index'

end

app/models/tag_group.rb
class TagGroup < ActiveRecord::Base
  attr_accessible :title

  has_many :tags

  validates :title, presence: true, uniqueness: true
end

app/controllers/tag_groups_controller.rb
class TagGroupsController < ApplicationController
  # GET /tag_groups
  # GET /tag_groups.json
  def index
    @tag_groups = TagGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tag_groups }
    end
  end

  # GET /tag_groups/1
  # GET /tag_groups/1.json
  def show
    @tag_group = TagGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag_group }
    end
  end

  # GET /tag_groups/new
  # GET /tag_groups/new.json
  def new
    @tag_group = TagGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag_group }
    end
  end

  # GET /tag_groups/1/edit
  def edit
    @tag_group = TagGroup.find(params[:id])
  end

  # POST /tag_groups
  # POST /tag_groups.json
  def create
    @tag_group = TagGroup.new(params[:tag_group])

    respond_to do |format|
      if @tag_group.save
        format.html { redirect_to tag_groups_url,
                      notice: 'Tag group was successfully created.' }
        format.json { render json: @tag_group, status: :created, location: @tag_group }
      else
        format.html { render action: "new" }
        format.json { render json: @tag_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tag_groups/1
  # PUT /tag_groups/1.json
  def update
    @tag_group = TagGroup.find(params[:id])

    respond_to do |format|
      if @tag_group.update_attributes(params[:tag_group])
        format.html { redirect_to tag_groups_url,
                      notice: 'Tag group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tag_groups/1
  # DELETE /tag_groups/1.json
  def destroy
    @tag_group = TagGroup.find(params[:id])
    @tag_group.destroy

    respond_to do |format|
      format.html { redirect_to tag_groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tag_groups_helper.rb
module TagGroupsHelper
end

app/views/tag_groups/_form.html.haml
= form_for @tag_group do |f|
  - if @tag_group.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tag_group.errors.count, "error")} prohibited this tag_group from being saved:"
      %ul
        - @tag_group.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/tag_groups/edit.html.haml
%h1 Editing tag_group

= render 'form'

= link_to 'Show', @tag_group
\|
= link_to 'Back', tag_groups_path

app/views/tag_groups/index.html.haml
%h1 Listing tag_groups

%table
  %tr
    %th Title
    %th
    %th

  - @tag_groups.each do |tag_group|
    %tr
      %td= tag_group.title
      %td= link_to 'Edit', edit_tag_group_path(tag_group)
      %td= link_to 'Destroy', tag_group,
                              method: :delete,
                              data: { :confirm => 'Are you sure?' }

%br

= link_to 'New Tag group', new_tag_group_path

app/views/tag_groups/new.html.haml
%h1 New tag_group

= render 'form'

= link_to 'Back', tag_groups_path

app/views/tag_groups/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @tag_group.title

= link_to 'Edit', edit_tag_group_path(@tag_group)
\|
= link_to 'Back', tag_groups_path