config/routes.rb
Butterflyicing::Application.routes.draw do

  resources :gallery_images
  resources :tags
  resources :tag_groups
  resources :users

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'image_manager' => 'image_manager#index'
  post 'image_manager' => 'image_manager#upload'
  delete 'image_manager' => 'image_manager#delete'
  get 'contactus' => 'contactus#index'
  post 'contactus' => 'contactus#send_message'
  get 'home' => 'home'
  get 'gallery/(:id)' => 'gallery#index' , as: :gallery
  get 'thumbnails/(:image_name)' => 'gallery#thumbnails'
  get 'ourcakes' => 'ourcakes#index'
  get 'weddings' => 'weddings#index'
  get 'cookies' => 'cookies#index'
  get 'parties' => 'parties#index'
  get 'contactus' => 'contactus#index'

  root :to => 'home#index'

end

app/models/gallery_image.rb
class GalleryImage < ActiveRecord::Base
  attr_accessible :tag_id, :image, :file_name
  attr_accessor  :file_type

  belongs_to :tag

  validates :file_type, allow_blank: false, unless: :persisted?, format: {
    with: /^image\/\w*(jpeg|png)\w*/,
    message: '--- you can only upload JPEG image files' #, allow_nil: true
  }

  before_destroy do |r|
    File.delete(r.image_file_path)
    File.delete(r.thumbnail_file_path)
  end

  def image_path
    "/images/gallery_images/#{file_name}"
  end

  def thumbnail_path
    "/thumbnails/#{file_name}"
  end

  def image_file_path
    Rails.root.join('public', 'images', 'gallery_images', file_name)
  end

  def image=(file)

    self.file_type = file.content_type.chomp

    if file && self.valid?
      require 'RMagick'

      self.file_name = "#{Time.now.to_i}.jpg"

      file.rewind
      file = Magick::Image::from_blob(file.read).first
      file.change_geometry!('640x480') { |cols, rows, img|
        file.resize!(cols, rows)
      }
      file.write(Rails.root.join('public', 'images', 'gallery_images', file_name))
    end
  end

end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :message

  validates :name, :email, :message, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => false

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :tag_group_id, :title

  has_many :gallery_images
  belongs_to :tag_group

  validates :title, presence: true
end

app/models/tag_group.rb
class TagGroup < ActiveRecord::Base
  attr_accessible :title

  has_many :tags

  validates :title, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation, :password_digest

#TODO add reset on next login
#TODO add email field
  validates :name, presence: true,
                   uniqueness: true,
                   format: {with: /(?=[a-zA-Z]{6,})/,
                            message: 'must be at least 6 characters and contain only upper and lowercase letters'
                   }

  validates :password, format: {
    with: /^.*(?=.{8,}).*$/,
    message: 'must be at least 8 characters long'
  }

  validates :password, format: {
    with: /^.*(?=.*[A-Z]).*$/,
    message: 'must contain at least one uppercase letter'
  }

  validates :password, format: {
    with: /^.*(?=.*[a-z]).*$/,
    message: 'must contain at least one lowercase letter'
  }

  validates :password, format: {
    with: /^.*(?=.*[\d]).*$/,
    message: 'must contain at least one digit (0-9)'
  }

  has_secure_password
  after_destroy :ensure_an_admin_remains

  private

    def ensure_an_admin_remains
      raise "Can't delete last user" if User.count.zero?
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/ourcakes_controller.rb
class OurcakesController < ApplicationController
  skip_before_filter :authorize

  def index
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.order('title')
    @tag_groups = TagGroup.order('title')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new
    @tag_groups = TagGroup.order('title')

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
    @tag_groups = TagGroup.order('title')
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])
    @tags = Tag.order('title')
    @tag_groups = TagGroup.order('title')

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tags_url, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])
    @tag_groups = TagGroup.order('title')

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to tags_url, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag_groups = TagGroup.order('title')
    tag_count = @tag.gallery_images.count

    if tag_count == 0
      @tag.destroy

      respond_to do |format|
        format.html { redirect_to tags_url, notice: 'Tag was removed.' }
        format.json { head :no_content }
      end
    else
      tag_count = view_context.pluralize(tag_count, 'image')
      respond_to do |format|
        format.html { redirect_to tags_url,
          notice: "Tag could not be reomved because it is being used by #{tag_count}" }
      end
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contactus_helper.rb
module ContactusHelper
end

app/helpers/cookies_helper.rb
module CookiesHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ourcakes_helper.rb
module OurcakesHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tag_groups_helper.rb
module TagGroupsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weddings_helper.rb
module WeddingsHelper
end

app/views/ourcakes/index.html.haml
- @title = 'Our Cakes'

%div.imgRotorLeft
  = image_tag "our_cakes1.jpg", class: "imgShow", size: '246x369'
  = image_tag "our_cakes2.jpg", class: "imgHide", size: '246x369'
  = image_tag "our_cakes3.jpg", class: "imgHide", size: '246x369'

%div.columnRight
  %h2 Cake Fillings - Storage and Shelf Life
  %ul.pinkList
    %li All cakes should be stored in a cool dark place on a flat sturdy surface.
    %li Never put cakes in the fridge other than fresh dairy cream cakes.
    %li Sponge, Chocolate and Carrot cake will keep for one week after delivery.
    %li Fruitcake lasts perfectly well, wrapped in foil, for months not years.
    %li We do not currently make gluten or dairy free cakes.
    %li Our sponge and chocolate cake does not contain nuts but may contain nut traces.
    %li Our fruitcake does contain nuts and alcohol.
    %li Our cakes are made with vegetable fats and contain dairy products.

  %h2 Vanilla Sponge
  %p
    Our vanilla sponge is made fresh to ensure a soft, moist and light texture. It is
    split and spread with a homemade butter-cream, whipped from pure butter and icing
    sugar. With choice of jam
  %h2 Chocolate Fudge Cake
  %p
    Our chocolate cake contains as much chocolate as we possibly can fit in. This ensures
    that it is always moist and rich in flavour. All of our chocolate cakes are topped
    with chocolate sugar paste icing and split with layers of butter-cream.
  %h2 Rich Fruit Cake
  %p
    Our fruitcake is packed full of fruit and flavours. We use natural ingredients real
    butter, dark sugar, flaked almonds, brandy and sun dried fruits. We slow bake the
    cakes in the oven to ensure a moist and delicious cake. We always finish our cakes
    with marzipan and rolled sugar icing.
  %h2 Carrot Cake
  %p
    Our carrot cake has been a favourite for over a decade. It is made from pure
    ingredients and fresh carrots to create a moist and delicious treat.
  %h2 Cup Cakes
  %p
    Our cup cakes can be made in any flavour from carrot to chocolate to traditional
    vanilla sponge. Will come boxed including a silver cup-cake stand to use for the
    day.
  %h2 FAQs
  %p
    %b How can I go about ordering my cake?
    %br/
    You can either email or telephone Joanne directly. All emails are responded to within
    24 hours.
  %ul
    %li Telephone: 07539-654-402
    %li
      = link_to 'Contact Us', contactus_path
    %li There is also a facebook group called Butterfly Icing

  %p
    %b When do I order my cake?
    %br/
    As soon as you can, once you know the occasion email or call Joanne and you can
    decide which cake is best for you.
  %p
    %b Do the cakes only come in one size?
    %br/
    A cake is made to suit your needs so will be as big or as small as required by you.
  %p
    %b I am not too sure what cake to decide on, can you help?
    %br/
    Sure, as long as you give Joanne an idea of who the person receiving the cake is,
    interests, hobbies, age etc, together we can come up with an idea.
  %p
    %b How much do the cakes cost?
    %br/
    The cost of the cake is dependant on how big/small it is and what type of cake you
    require. All quotes are done instantly, so call Joanne for a quote.
  %p
    %b How is the cake collected and when?
    %br/
    The cakes can be collected from Joanne once they are ready. Collection is usually
    done the day before the event or in some instances on the day.
  %p
    %b I forgot to order a cake and need a rush order, can you help?
    %br/
    This is dependant on how busy we are; although we will try our best to help you,
    this will totally depend on when you order, so if this is the case call Joanne
    immediately and she will be glad to help.