config/routes.rb
Butterflyicing::Application.routes.draw do

  resources :gallery_images
  resources :tags
  resources :tag_groups
  resources :users

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'image_manager' => 'image_manager#index'
  post 'image_manager' => 'image_manager#upload'
  delete 'image_manager' => 'image_manager#delete'
  get 'contactus' => 'contactus#index'
  post 'contactus' => 'contactus#send_message'
  get 'home' => 'home'
  get 'gallery/(:id)' => 'gallery#index' , as: :gallery
  get 'thumbnails/(:image_name)' => 'gallery#thumbnails'
  get 'ourcakes' => 'ourcakes#index'
  get 'weddings' => 'weddings#index'
  get 'cookies' => 'cookies#index'
  get 'parties' => 'parties#index'
  get 'contactus' => 'contactus#index'

  root :to => 'home#index'

end

app/models/gallery_image.rb
class GalleryImage < ActiveRecord::Base
  attr_accessible :tag_id, :image, :file_name
  attr_accessor  :file_type

  belongs_to :tag

  validates :file_type, allow_blank: false, unless: :persisted?, format: {
    with: /^image\/\w*(jpeg|png)\w*/,
    message: '--- you can only upload JPEG image files' #, allow_nil: true
  }

  before_destroy do |r|
    File.delete(r.image_file_path)
    File.delete(r.thumbnail_file_path)
  end

  def image_path
    "/images/gallery_images/#{file_name}"
  end

  def thumbnail_path
    "/thumbnails/#{file_name}"
  end

  def image_file_path
    Rails.root.join('public', 'images', 'gallery_images', file_name)
  end

  def image=(file)

    self.file_type = file.content_type.chomp

    if file && self.valid?
      require 'RMagick'

      self.file_name = "#{Time.now.to_i}.jpg"

      file.rewind
      file = Magick::Image::from_blob(file.read).first
      file.change_geometry!('640x480') { |cols, rows, img|
        file.resize!(cols, rows)
      }
      file.write(Rails.root.join('public', 'images', 'gallery_images', file_name))
    end
  end

end

app/controllers/gallery_images_controller.rb
class GalleryImagesController < ApplicationController
  # GET /gallery_images
  # GET /gallery_images.json
  def index
    @gallery_image = GalleryImage.new
    @gallery_images = GalleryImage.all
    @tag_groups = TagGroup.order('title')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gallery_images }
    end
  end

  # GET /gallery_images/1
  # GET /gallery_images/1.json
  def show
    @gallery_image = GalleryImage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery_image }
    end
  end

  # GET /gallery_images/new
  # GET /gallery_images/new.json
  def new
    @gallery_image = GalleryImage.new
    @tag_groups = TagGroup.order('title')

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gallery_image }
    end
  end

  # GET /gallery_images/1/edit
  def edit
    @gallery_image = GalleryImage.find(params[:id])
    @tag_groups = TagGroup.order('title')
  end

  # POST /gallery_images
  # POST /gallery_images.json
  def create
    @gallery_image = GalleryImage.new(params[:gallery_image])
    @gallery_images = GalleryImage.all
    @tag_groups = TagGroup.order('title')

    respond_to do |format|
      if @gallery_image.save
        format.html { redirect_to gallery_images_url, notice:
                      'Gallery image was successfully created.' }
        format.json { render json: @gallery_image, status:
                      :created, location: @gallery_image }
      else
        format.html { render action: "index" }
        format.json { render json: @gallery_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gallery_images/1
  # PUT /gallery_images/1.json
  def update
    @gallery_image = GalleryImage.find(params[:id])
    @tag_groups = TagGroup.order('title')

    respond_to do |format|
      if @gallery_image.update_attributes(params[:gallery_image])
        format.html { redirect_to gallery_images_url,
                      notice: 'Gallery image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gallery_image.errors,
                      status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gallery_images/1
  # DELETE /gallery_images/1.json
  def destroy
    @gallery_image = GalleryImage.find(params[:id])
    @gallery_image.destroy

    respond_to do |format|
      format.html { redirect_to gallery_images_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/gallery_images_helper.rb
module GalleryImagesHelper
end

app/views/gallery_images/_form.html.haml
= form_for @gallery_image, nultipart: true do |f|
  - if @gallery_image.errors.any?
    #error_explanation
      %h2= "#{pluralize(@gallery_image.errors.count,
        "error")} prohibited this gallery_image from being saved:"
      %ul
        - @gallery_image.errors.full_messages.each do |msg|
          %li= msg

  %div.field
    = f.label :image, 'Select image file: '
    = f.file_field :image, size: 5
  %div.field
    = f.label :tag_id, 'Select category: '
    = f.grouped_collection_select(:tag_id, @tag_groups,
      :tags, :title, :id, :title, {selected: f.object.tag_id})
  %div.actions
    = f.submit 'Upload'

app/views/gallery_images/edit.html.haml
%h1 Editing gallery_image

= render 'form'

= link_to 'Show', @gallery_image
\|
= link_to 'Back', gallery_images_path

app/views/gallery_images/index.html.haml
- @title = 'Image Manager'
%h2 Image Manager
%p
  Use the file selector below to pick an image you want to upload, make
  sure that use the drop-down to select which category you want the image
  displayed under. To remove an image click the link below it from the display below.

%div
  = render 'form'

%div#galleryDisplay
  - @gallery_images.sort{|a, b| a.tag.title <=> b.tag.title}.each do |gallery_image|
    %div.galleryItem
      = link_to(image_tag(gallery_image.thumbnail_path,
        {size: '100x100'}),
        gallery_image.image_path, class: 'lightBox')
      %br
      %td= link_to 'Remove', gallery_image,
        method: :delete,
        data: { confirm: 'Are you sure?' }
      = form_for gallery_image, remote: true do |f|
        = f.grouped_collection_select :tag_id, @tag_groups,
          :tags, :title, :id, :title, {selected: f.object.tag_id}

app/views/gallery_images/new.html.haml
%h1 New gallery_image

= render 'form'

= link_to 'Back', gallery_images_path

app/views/gallery_images/show.html.haml
%p#notice= notice

%p
  %b Tag:
  = @gallery_image.tag_id

= link_to 'Edit', edit_gallery_image_path(@gallery_image)
\|
= link_to 'Back', gallery_images_path